spring.application.name=biblioteca-demo
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/biblioteca}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:biblioteca}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:biblioteca}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
